apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: turbine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: turbine
    app.kubernetes.io/part-of: turbine
  name: turbine
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: turbine
status:
  loadBalancer: {}
